version: "3.9"
services:
  client:
    image: golang:latest
    working_dir: "/client"
    networks:
      example:
        ipv4_address: 172.16.0.5
    volumes:
      - ./client:/client
    command: tail -f /dev/null
  server:
    image: golang:latest
    working_dir: "/server"
    networks:
      example:
        ipv4_address: 172.16.0.6
    volumes:
      - ./server:/server
    command: tail -f /dev/null
networks:
  example:
    name: example
    external: true
