version: "3.9"
services:
  client:
    image: golang:latest
    container_name: go-client
    working_dir: "/client"
    networks:
      - example
    volumes:
      - ./client:/client
    command: tail -f /dev/null
  server:
    image: golang:latest
    container_name: go-server
    working_dir: "/server"
    networks:
      - example
    volumes:
      - ./server:/server
    command: tail -f /dev/null
networks:
  example:
